Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vbguest.auto_update = true

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.inventory_path = "example-inventory/dev"
    ansible.provisioning_path = "/vagrant/data-science-hub"
    ansible.raw_arguments = ['-u vagrant']
  end

  config.vm.synced_folder "..", "/vagrant", type: "virtualbox"

  #config.vm.network :forwarded_port, guest: 22, host: 2223

  config.vm.define "bdr-data-science-hub", autostart: true do |vm|
      vm.vm.hostname = "bdr-data-science-hub"
      vm.vm.network "private_network", ip: "10.0.0.43"
      vm.vm.synced_folder "../../", "/home/vagrant/projects",  :mount_options => ["dmode=644,fmode=644"]

      # Provision virtualbox:
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 4
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
  end


end
