name: xgboost
dependencies:
- python=2.7
- certifi==2016.2.28
- cycler==0.10.0
- matplotlib==2.0.2
- numpy==1.13.1
- pandas==0.20.3
- pyparsing==2.2.0
- python-dateutil==2.6.1
- pytz==2017.2
- scikit-learn==0.19.0
- scipy==0.19.1
- six==1.10.0
- scikit-learn>=0.18
- jupyter
- seaborn
- pip
- pip:
  - -rrequirements.txt