---
- hosts: all

# Note that the variables here must match spark_kernels.yml
  roles:
    - { role: anaconda, anaconda_install_dir: "{{ ansible_env.HOME }}/anaconda3", anaconda_url: "https://repo.continuum.io/archive/Anaconda3-4.2.0-MacOSX-x86_64.sh" }
    - { role: spark_client, spark_client_version: "1.6.3-hadoop-2.6", spark_client_url: "http://d3kbcqa49mib13.cloudfront.net/spark-1.6.3-bin-hadoop2.6.tgz"}
    - { role: spark_client, spark_client_version: "2.0.2-hadoop-2.7", spark_client_url: "http://d3kbcqa49mib13.cloudfront.net/spark-2.0.2-bin-hadoop2.7.tgz"}
    - { role: brew}


