Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
   config.ssh.insert_key = false
   config.vbguest.auto_update = true

   config.vm.provision "ansible_local" do |ansible|
     ansible.playbook = "provision.yml"
     ansible.inventory_path = "example-inventory/dev"
     ansible.provisioning_path = "/vagrant/search-box"
     ansible.raw_arguments = ['-u vagrant']
  end

  config.vm.synced_folder "..", "/vagrant", type: "virtualbox"

  config.vm.define "bdr-elk-security-stack", autostart: true do |vm|
      vm.vm.hostname = "bdr-elk-security-stack"
      vm.vm.network "private_network", ip: "10.0.0.21"

      # Provision virtualbox:
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 4000 #12288 # 12 GB
        vb.cpus = 4
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
  end


end
